#!/usr/bin/env bash
# =============================================================================
# BRIVIA deployment for cPanel (Namecheap shared hosting). Invoked by .cpanel.yml
# when you press "Deploy HEAD Commit" in cPanel → Git Version Control.
#
# What it does, in order (nothing in the live app changes until step 6):
#   1. Lock (one deployment at a time) and identify the exact HEAD commit of the cPanel clone.
#   2. Preflight the live app: production .env with APP_KEY present (never generated here).
#   3. Download ONLY the GitHub release build-<that commit's full SHA> (never "latest"), verify
#      its SHA-256 checksum, archive paths, Vite manifest and recorded source SHA.
#   4. Stage the exact commit (git archive), add the verified assets, install production
#      Composer dependencies from composer.lock (no dev packages) — all outside the live app.
#   5. Back up the database (and abort if that fails).
#   6. Maintenance mode → rsync code into the live app (preserving .env, storage, uploads,
#      logs, public/storage, public/.well-known and cPanel PHP settings) → migrate --force →
#      storage link → rebuild caches → queue restart → maintenance off → health check.
#
# Never runs: migrate:fresh/reset/refresh, db:seed, demo seeders, key:generate.
# Touches only: $APP_DIR, $STATE_DIR (~/.brivia-deploy), $BACKUP_DIR (~/brivia-backups).
#
# Dry run (all checks + staging + "what would change", no live changes, no backup):
#   BRIVIA_DEPLOY_DRY_RUN=1 bash scripts/deploy.sh
# =============================================================================
set -Eeuo pipefail
umask 022

# ---------- Configuration (production defaults; overridable only for testing) ----------
APP_DIR="${BRIVIA_APP_DIR:-/home/fitcbfra/brivia-app}"
PHP_BIN="${BRIVIA_PHP_BIN:-/opt/alt/php83/usr/bin/php}"
COMPOSER_BIN="${BRIVIA_COMPOSER_BIN:-/home/fitcbfra/bin/composer}"
GITHUB_REPO="${BRIVIA_GITHUB_REPO:-mfakih7/Brivia}"
RELEASE_BASE_URL="${BRIVIA_RELEASE_BASE_URL:-https://github.com/$GITHUB_REPO/releases/download}"
STATE_DIR="${BRIVIA_STATE_DIR:-$HOME/.brivia-deploy}"
BACKUP_DIR="${BRIVIA_BACKUP_DIR:-$HOME/brivia-backups}"
DRY_RUN="${BRIVIA_DEPLOY_DRY_RUN:-0}"
SKIP_DB_BACKUP="${BRIVIA_DEPLOY_SKIP_DB_BACKUP:-0}"
KEEP_BACKUPS=10
KEEP_LOGS=30
MAX_ARCHIVE_BYTES=$((50 * 1024 * 1024))

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TIMESTAMP="$(date -u +%Y%m%dT%H%M%SZ)"
STAGE=""
LOCK_MODE=""
MAINTENANCE_ON=0
LIVE_CHANGED=0

# ---------- Output ----------
mkdir -p "$STATE_DIR/logs"
chmod 700 "$STATE_DIR"
LOG_FILE="$STATE_DIR/logs/deploy-$TIMESTAMP.log"
exec > >(tee -a "$LOG_FILE") 2>&1

log()  { printf '[%s] %s\n' "$(date -u +%H:%M:%S)" "$*"; }
warn() { printf '[%s] WARNING: %s\n' "$(date -u +%H:%M:%S)" "$*"; }
die()  { printf '[%s] ERROR: %s\n' "$(date -u +%H:%M:%S)" "$*"; failure_summary 1; exit 1; }

on_error() { failure_summary "$?"; }

failure_summary() {
    local code="$1"
    trap - ERR
    echo
    if [[ "$LIVE_CHANGED" == "1" ]]; then
        echo "DEPLOYMENT FAILED AFTER LIVE FILES CHANGED (exit $code)."
        if [[ "$MAINTENANCE_ON" == "1" ]]; then
            echo "The site was left in maintenance mode on purpose so visitors do not see a half-updated app."
        else
            echo "This was a first deployment (no previous app to put in maintenance mode); the site is not usable yet."
        fi
        echo "Recover: fix the cause shown above, then press 'Deploy HEAD Commit' again (safe to repeat),"
        echo "or restore the previous release (see DEPLOYMENT.md → Rollback). To lift maintenance manually:"
        echo "  cd $APP_DIR && $PHP_BIN artisan up"
        echo "Database backup taken before this run: ${DB_BACKUP_FILE:-none}"
    elif [[ "$MAINTENANCE_ON" == "1" ]]; then
        "$PHP_BIN" "$APP_DIR/artisan" up >/dev/null 2>&1 || true
        echo "DEPLOYMENT FAILED (exit $code). No live code was changed; maintenance mode was lifted."
    else
        echo "DEPLOYMENT FAILED (exit $code). No live files were changed."
    fi
    echo "Full log: $LOG_FILE"
}
trap on_error ERR

cleanup() {
    [[ -n "$STAGE" && -d "$STAGE" ]] && rm -rf "$STAGE"
    if [[ "$LOCK_MODE" == "mkdir" ]]; then rmdir "$STATE_DIR/deploy.lock.d" 2>/dev/null || true; fi
    # Keep the newest logs only (names are generated by this script: no spaces).
    # shellcheck disable=SC2012
    ls -1t "$STATE_DIR"/logs/deploy-*.log 2>/dev/null | tail -n +$((KEEP_LOGS + 1)) | xargs -r rm -f
}
trap cleanup EXIT

# ---------- Helpers ----------
# Reads KEY from the live .env without sourcing it (values are never printed).
env_value() {
    local key="$1" line value
    line="$(grep -E "^${key}=" "$APP_DIR/.env" | tail -n 1 || true)"
    value="${line#*=}"
    value="${value%$'\r'}"
    if [[ "$value" =~ ^\"(.*)\"$ ]]; then value="${BASH_REMATCH[1]}"; elif [[ "$value" =~ ^\'(.*)\'$ ]]; then value="${BASH_REMATCH[1]}"; fi
    printf '%s' "$value"
}

# Not a subshell, so the ERR trap reports a failure exactly once. Artisan resolves paths from its own directory.
artisan() { "$PHP_BIN" "$APP_DIR/artisan" "$@" --no-interaction --no-ansi; }

run_composer() {
    # The Composer path may be the phar itself or a wrapper; always force PHP 8.3 for the phar.
    if head -c 200 "$COMPOSER_BIN" | grep -qE '^#!.*(php|env php)'; then
        "$PHP_BIN" "$COMPOSER_BIN" "$@"
    elif head -c 4 "$COMPOSER_BIN" | grep -q '<?ph'; then
        "$PHP_BIN" "$COMPOSER_BIN" "$@"
    else
        PATH="$(dirname "$PHP_BIN"):$PATH" "$COMPOSER_BIN" "$@"
    fi
}

# =============================================================================
log "BRIVIA deployment started ($([[ "$DRY_RUN" == "1" ]] && echo DRY RUN || echo LIVE))"

# ---------- 1. Safety checks and lock ----------
case "$APP_DIR" in
    */brivia-app) ;;
    *) [[ "${BRIVIA_DEPLOY_ALLOW_ANY_APP_DIR:-0}" == "1" ]] || die "APP_DIR '$APP_DIR' does not end in /brivia-app; refusing to touch other applications." ;;
esac
[[ "$APP_DIR" != "$REPO_DIR" && "$APP_DIR" != "/" && "$APP_DIR" != "$HOME" ]] || die "Unsafe APP_DIR '$APP_DIR'."
[[ -x "$PHP_BIN" ]] || die "PHP not found at $PHP_BIN"
[[ -f "$COMPOSER_BIN" ]] || die "Composer not found at $COMPOSER_BIN"
for tool in git tar curl sha256sum gzip; do command -v "$tool" >/dev/null || die "Required tool '$tool' not found"; done
if [[ "$DRY_RUN" != "1" ]]; then command -v rsync >/dev/null || die "rsync not found"; fi

if command -v flock >/dev/null 2>&1; then
    exec 9>"$STATE_DIR/deploy.lock"
    flock -n 9 || die "Another BRIVIA deployment is running. Wait for it to finish, then retry."
    LOCK_MODE="flock"
else
    mkdir "$STATE_DIR/deploy.lock.d" 2>/dev/null || die "Another BRIVIA deployment is running (lock: $STATE_DIR/deploy.lock.d). If none is, remove that directory."
    LOCK_MODE="mkdir"
fi

PHP_VERSION="$("$PHP_BIN" -r 'echo PHP_VERSION;')"
"$PHP_BIN" -r 'exit(version_compare(PHP_VERSION, "8.3.0", ">=") ? 0 : 1);' || die "PHP $PHP_VERSION is too old; Laravel 13 needs 8.3+"
log "PHP $PHP_VERSION ($PHP_BIN)"

SHA="$(git -C "$REPO_DIR" rev-parse --verify 'HEAD^{commit}')"
[[ "$SHA" =~ ^[0-9a-f]{40}$ ]] || die "Could not resolve the HEAD commit of $REPO_DIR"
BRANCH="$(git -C "$REPO_DIR" rev-parse --abbrev-ref HEAD || true)"
log "Deploying commit $SHA (branch: $BRANCH) from $REPO_DIR"
[[ "$BRANCH" == "main" ]] || warn "The cPanel clone is on '$BRANCH', not 'main'."
if [[ -n "$(git -C "$REPO_DIR" status --porcelain 2>/dev/null)" ]]; then
    warn "The clone has local modifications; they are ignored (only the committed HEAD is deployed)."
fi

# ---------- 2. Preflight the live application ----------
mkdir -p "$APP_DIR"
[[ -f "$APP_DIR/.env" ]] || die "Missing $APP_DIR/.env. Create it from .env.production.example first (see DEPLOYMENT.md). Nothing was changed."
APP_KEY_VALUE="$(env_value APP_KEY)"
[[ "$APP_KEY_VALUE" =~ ^base64:.{40,}$ ]] || die "APP_KEY in $APP_DIR/.env is missing or invalid. Generate it once as documented; this script never creates one."
unset APP_KEY_VALUE
[[ "$(env_value APP_ENV)" == "production" ]] || warn "APP_ENV is not 'production'."
[[ "$(env_value APP_DEBUG)" == "false" ]] || warn "APP_DEBUG is not 'false'; never leave debug on in production."
APP_URL_VALUE="$(env_value APP_URL)"
DB_CONNECTION_VALUE="$(env_value DB_CONNECTION)"
PREVIOUS_SHA="$(cat "$APP_DIR/storage/app/deploy/current-release" 2>/dev/null | head -n1 || true)"
log "Previously deployed: ${PREVIOUS_SHA:-none recorded}"

# ---------- 3. Fetch and verify the matching frontend build ----------
STAGE="$STATE_DIR/stage-$TIMESTAMP"
mkdir -p "$STAGE/download" "$STAGE/frontend" "$STAGE/src"
ASSET="brivia-frontend-$SHA.tar.gz"
ASSET_URL="$RELEASE_BASE_URL/build-$SHA/$ASSET"
log "Fetching frontend build for this exact commit: build-$SHA"
if ! curl -fsSL --retry 3 --retry-delay 5 --connect-timeout 20 --max-time 300 -o "$STAGE/download/$ASSET" "$ASSET_URL" \
    || ! curl -fsSL --retry 3 --retry-delay 5 --connect-timeout 20 --max-time 60 -o "$STAGE/download/$ASSET.sha256" "$ASSET_URL.sha256"; then
    die "Frontend build 'build-$SHA' is not available yet. Wait until the GitHub 'Frontend build' workflow for this commit has succeeded, then deploy again. Nothing was changed."
fi

size="$(wc -c < "$STAGE/download/$ASSET")"
(( size > 0 && size < MAX_ARCHIVE_BYTES )) || die "Unexpected archive size ($size bytes)."

read -r expected_sum expected_name < "$STAGE/download/$ASSET.sha256"
[[ "${expected_name#\*}" == "$ASSET" ]] || die "Checksum file names '$expected_name', expected '$ASSET'."
actual_sum="$(sha256sum "$STAGE/download/$ASSET" | cut -d' ' -f1)"
[[ "$expected_sum" =~ ^[0-9a-f]{64}$ && "$actual_sum" == "$expected_sum" ]] || die "SHA-256 mismatch for $ASSET (expected $expected_sum, got $actual_sum)."
log "Checksum OK ($actual_sum)"

# Archive must contain only regular files/directories under build/, with no traversal.
while IFS= read -r entry; do
    case "$entry" in
        build/|build/*) ;;
        *) die "Archive contains an unexpected path: '$entry'" ;;
    esac
    [[ "$entry" != *".."* && "$entry" != /* ]] || die "Archive contains an unsafe path: '$entry'"
done < <(tar -tzf "$STAGE/download/$ASSET")
member_types="$(tar -tvzf "$STAGE/download/$ASSET" | cut -c1 | sort -u | tr -d '\n')"
[[ "$member_types" =~ ^[-d]+$ ]] || die "Archive contains links or special files (types: $member_types); refusing."
tar -xzf "$STAGE/download/$ASSET" -C "$STAGE/frontend" --no-same-owner --no-same-permissions

BUILD="$STAGE/frontend/build"
# shellcheck disable=SC2016 # single quotes are intentional: this is PHP code
"$PHP_BIN" -r '
    [$build, $sha] = [$argv[1], $argv[2]];
    $info = json_decode((string) @file_get_contents("$build/build-info.json"), true);
    if (($info["source_sha"] ?? null) !== $sha) { fwrite(STDERR, "build-info.json source_sha does not match $sha\n"); exit(1); }
    $manifest = json_decode((string) @file_get_contents("$build/manifest.json"), true);
    if (! is_array($manifest)) { fwrite(STDERR, "manifest.json is missing or invalid JSON\n"); exit(1); }
    foreach (["resources/css/app.css", "resources/js/app.js"] as $entry) {
        if (empty($manifest[$entry]["file"])) { fwrite(STDERR, "manifest.json lacks entry $entry\n"); exit(1); }
    }
    foreach ($manifest as $chunk) {
        foreach (array_merge([$chunk["file"] ?? null], $chunk["css"] ?? [], $chunk["assets"] ?? []) as $file) {
            if ($file === null) { continue; }
            if (str_contains($file, "..") || ! is_file("$build/$file")) { fwrite(STDERR, "manifest references missing/unsafe file: $file\n"); exit(1); }
        }
    }
    echo "Vite manifest OK (".count($manifest)." entries)\n";
' "$BUILD" "$SHA" || die "Frontend build verification failed."

# ---------- 4. Stage the exact commit and install production dependencies ----------
log "Staging commit $SHA (git archive; Git metadata and untracked files are never deployed)"
git -C "$REPO_DIR" archive --format=tar "$SHA" | tar -xf - -C "$STAGE/src"
[[ -f "$STAGE/src/composer.lock" ]] || die "composer.lock missing from the commit."

# Development-only material never reaches the live app.
( cd "$STAGE/src" && rm -rf \
    .github .cpanel.yml scripts tests docs node_modules storage public/storage public/hot public/build \
    .env .env.backup .env.example .env.production.example .editorconfig .gitattributes .gitignore .nvmrc \
    phpunit.xml package.json package-lock.json vite.config.js resources/css resources/js \
    AGENTS.md CLAUDE.md database/database.sqlite )
cp -R "$BUILD" "$STAGE/src/public/build"

log "Installing production Composer dependencies from composer.lock"
export COMPOSER_NO_INTERACTION=1 COMPOSER_NO_AUDIT=1
run_composer --version --no-ansi 2>/dev/null | sed -n 1p
run_composer check-platform-reqs --no-dev --lock --working-dir="$STAGE/src" --no-ansi >/dev/null \
    || die "The server PHP is missing extensions or versions required by composer.lock (run 'composer check-platform-reqs --no-dev' for details)."
run_composer install --working-dir="$STAGE/src" --no-dev --prefer-dist --no-progress --no-scripts --optimize-autoloader --no-ansi

# ---------- Dry run stops here ----------
if [[ "$DRY_RUN" == "1" ]]; then
    log "DRY RUN: all checks passed. Changes rsync would make in $APP_DIR:"
    if command -v rsync >/dev/null; then
        rsync -a --delete --dry-run --itemize-changes --exclude-from=- "$STAGE/src/" "$APP_DIR/" <<'EXCLUDES' | grep -vE '/vendor/' | head -n 200 || true
/.env
/.env.*
/storage/
/public/storage
/public/.well-known/
/public/.user.ini
/public/php.ini
/public/error_log
/.user.ini
/php.ini
/error_log
/.htaccess
/bootstrap/cache/*.php
EXCLUDES
    else
        warn "rsync not available here; skipped the change listing."
    fi
    log "DRY RUN complete. Nothing in $APP_DIR was changed and no backup was taken."
    exit 0
fi

# ---------- 5. Database backup (before any live change) ----------
DB_BACKUP_FILE=""
if [[ "$SKIP_DB_BACKUP" == "1" ]]; then
    warn "Database backup skipped (BRIVIA_DEPLOY_SKIP_DB_BACKUP=1)."
else
    mkdir -p "$BACKUP_DIR" && chmod 700 "$BACKUP_DIR"
    case "$DB_CONNECTION_VALUE" in
        mysql|mariadb)
            command -v mysqldump >/dev/null || die "mysqldump not found; cannot back up before migrating. Nothing was changed."
            cnf="$STAGE/db.cnf"
            ( umask 077
              esc() { local v="$1"; v="${v//\\/\\\\}"; v="${v//\"/\\\"}"; printf '%s' "$v"; }
              printf '[client]\nuser="%s"\npassword="%s"\nhost="%s"\nport="%s"\n' \
                  "$(esc "$(env_value DB_USERNAME)")" "$(esc "$(env_value DB_PASSWORD)")" \
                  "$(esc "$(env_value DB_HOST)")" "$(esc "$(env_value DB_PORT)")" > "$cnf" )
            DB_BACKUP_FILE="$BACKUP_DIR/brivia-db-$TIMESTAMP-before-${SHA:0:12}.sql.gz"
            ( umask 077
              mysqldump --defaults-extra-file="$cnf" --single-transaction --quick --routines --no-tablespaces \
                  "$(env_value DB_DATABASE)" | gzip -9 > "$DB_BACKUP_FILE" ) \
                || { rm -f "$cnf" "$DB_BACKUP_FILE"; die "Database backup failed. Nothing was changed."; }
            rm -f "$cnf"
            gzip -t "$DB_BACKUP_FILE" || die "Database backup is corrupt. Nothing was changed."
            ;;
        sqlite)
            db_path="$(env_value DB_DATABASE)"
            [[ -f "$db_path" ]] && { DB_BACKUP_FILE="$BACKUP_DIR/brivia-db-$TIMESTAMP.sqlite"; cp "$db_path" "$DB_BACKUP_FILE"; chmod 600 "$DB_BACKUP_FILE"; }
            ;;
        *) die "Unsupported DB_CONNECTION '$DB_CONNECTION_VALUE' for automatic backup. Nothing was changed." ;;
    esac
    [[ -n "$DB_BACKUP_FILE" ]] && log "Database backup: $DB_BACKUP_FILE ($(wc -c < "$DB_BACKUP_FILE") bytes)"
    # shellcheck disable=SC2012 # backup names are generated by this script
    ls -1t "$BACKUP_DIR"/brivia-db-* 2>/dev/null | tail -n +$((KEEP_BACKUPS + 1)) | xargs -r rm -f
fi

# ---------- 6. Switch the live application ----------
if [[ -f "$APP_DIR/artisan" && -f "$APP_DIR/vendor/autoload.php" ]]; then
    log "Enabling maintenance mode"
    if artisan down --retry=60 >/dev/null; then
        MAINTENANCE_ON=1
    else
        warn "Could not enable maintenance mode; continuing."
    fi
fi

# Keep the PHP handler lines that cPanel (MultiPHP) writes into public/.htaccess.
HANDLER_BLOCK=""
if [[ -f "$APP_DIR/public/.htaccess" ]]; then
    HANDLER_BLOCK="$(sed -n '/# php -- BEGIN cPanel-generated handler/,/# php -- END cPanel-generated handler/p' "$APP_DIR/public/.htaccess")"
fi

LIVE_CHANGED=1
log "Synchronising code into $APP_DIR"
rsync -a --delete --delay-updates --exclude-from=- "$STAGE/src/" "$APP_DIR/" <<'EXCLUDES'
/.env
/.env.*
/storage/
/public/storage
/public/.well-known/
/public/.user.ini
/public/php.ini
/public/error_log
/.user.ini
/php.ini
/error_log
/.htaccess
/bootstrap/cache/*.php
EXCLUDES

if [[ -n "$HANDLER_BLOCK" ]] && ! grep -q '# php -- BEGIN cPanel-generated handler' "$APP_DIR/public/.htaccess"; then
    printf '\n%s\n' "$HANDLER_BLOCK" >> "$APP_DIR/public/.htaccess"
    log "Restored the cPanel PHP handler block in public/.htaccess"
fi

mkdir -p "$APP_DIR"/storage/app/public "$APP_DIR"/storage/app/deploy "$APP_DIR"/storage/framework/{cache/data,sessions,views} \
    "$APP_DIR"/storage/logs "$APP_DIR"/bootstrap/cache

log "Running Laravel tasks"
artisan package:discover
# File-based caches only: the database cache table may not exist yet on a first deployment.
artisan config:clear
artisan route:clear
artisan view:clear
artisan event:clear
artisan migrate --force
if [[ ! -e "$APP_DIR/public/storage" ]]; then
    artisan storage:link
fi
artisan optimize
artisan queue:restart

printf '%s\n%s\n' "$SHA" "$TIMESTAMP" > "$APP_DIR/storage/app/deploy/current-release"
printf '%s deployed %s (previous %s) backup=%s\n' "$TIMESTAMP" "$SHA" "${PREVIOUS_SHA:-none}" "${DB_BACKUP_FILE:-none}" >> "$APP_DIR/storage/app/deploy/history.log"

if [[ "$MAINTENANCE_ON" == "1" ]]; then artisan up >/dev/null; MAINTENANCE_ON=0; fi
LIVE_CHANGED=0
log "Commit $SHA is live."

# ---------- Health check ----------
if [[ -n "$APP_URL_VALUE" ]]; then
    if curl -fsS --max-time 20 -o /dev/null "$APP_URL_VALUE/up"; then
        log "Health check OK: $APP_URL_VALUE/up"
    else
        warn "Health check failed for $APP_URL_VALUE/up. Check storage/logs/laravel.log and the site in a browser."
        exit 2
    fi
fi
log "Deployment finished successfully."
